
# Get and set  paths -------------------------------------------------------
source("path/path.R") #get paths

# Load packages -----------------------------------------------------------

require(xfun)
require(modelsummary)
require(GJRM)
require(cli)
require(rlang)
require(dplyr)
require(gratia)
require(mgcv)
require(Cairo)
require(ggplot2)
require(readr)
require(tidyr)
require(stringr)
require(stringi)
require(magrittr)
require(readr)
require(tidyr)
require(lme4)
require(lmtest)
require(table1)
require(cowplot)
require(BAS)
require(jstable)
require(kableExtra)
require(tableone)
require(purrr)
require(MASS)
require(conflicted)
require(sf)
require(car)
require(rnaturalearth)
require(ggtext)
require(ggpubr)
require(tinytex)
require(cowplot)
require(performance)
require(plm)
require(caret)
require(pROC)
require(VGAM)
require(labelled)

#manage package conflicts
conflict_prefer("get_legend","cowplot")
conflict_prefer("filter","dplyr")
conflict_prefer("select","dplyr")
conflict_prefer("mutate","dplyr")
conflict_prefer("filter","dplyr")
conflict_prefer("summarize","dplyr")
conflict_prefer("label","Hmisc")
conflict_prefer("rowSums","base")
conflict_prefer("head","utils")
conflicted::conflicts_prefer(lmtest::lrtest)
